### ISSUE TITLE
World file incorrect when setting Image resolution

### ISSUE THREAD

**Issue by perrygeo** [OSUCartography/PyramidShader#27]
Awesome software, makes it very easy to explore some beautiful terrain visualizations!

When saving a contour image as png, if I set "Image resolution relative to terrain model size" equal to 1, I get a valid pgw file. But If I increase the resolution, I get the same exact pgw which leads to incorrect georeferencing. The first and fourth lines (indicating the cell size) need to be adjusted according to the resolution parameter.

**Comment by berniejenny** [comment]
Thanks for the bug report. This should be fixed with release 1.0.1.
